name: 새로운 책
description: 2022년에 같이 읽어볼 책 추가하기
labels: [책]
body:
  - type: markdown
    attributes:
      value: |
        2022년에 같이 읽어볼 책을 추가합니다. **특정 직군에 국한된 책은 가능한 지양해주세요.**
  - type: textarea
    id: book-title
    attributes:
      label: 책 설명
      description: 간단하게 책을 설명해주세요.
      placeholder: 책 설명
    validations:
      required: true
